[package]
name = "tui-explorer"
version = "0.1.0"
authors = ["Paweł Osuch <osuch@wsisiz.edu.pl>"]
license = "MIT"
edition = "2021"

[dependencies]
chrono = "0.4.34"
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures = "0.3.30"
ratatui = "0.26.0"
tokio = { version = "1.35.1", features = ["full"] }
